# Generated by Django 2.2.4 on 2019-08-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='titulo',
            field=models.TextField(blank=True, verbose_name='titulo'),
        ),
    ]
