# Generated by Django 2.2.4 on 2019-08-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_posts_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='titulo',
            field=models.CharField(blank=True, max_length=30, verbose_name='titulo'),
        ),
    ]
