# Generated by Django 2.2.4 on 2019-08-07 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='post',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='posts.Posts', verbose_name='post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='comentario',
            field=models.TextField(verbose_name='comentario'),
        ),
    ]
