# Generated by Django 2.2.4 on 2019-08-07 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Categorias',
        ),
        migrations.RenameField(
            model_name='categorias',
            old_name='categoria',
            new_name='categorias',
        ),
    ]
